### ISSUE TITLE
Slack integration test

### ISSUE THREAD

**Issue by keitaito** [keitaito/MenMa#9]
To confirm if issue open notification will be sent to Slack.

**Comment by keitaito** [comment]
It works! Yay :octocat:

**Comment by lynneokada** [comment]
aaaaayyyyy :+1:

**Comment by keitaito** [comment]
@lynneokada Hahaha, I'm busted :stuck_out_tongue_winking_eye: I did this secretly. How did you find it? Did you get a notification?
